---
- hosts: all  #group name from the inventory
#user: ec2-user Server Auth
  sudo: true


  tasks:
    - name: Add a list of users
      user: name={{ item }} state=present
      with_items:
        - Tom 
        - Dick 
        - Harry 
...

